name: Deploy PDF

# Controls when the action will run
on:
  push:
    branches:
      - main
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  compile:
    uses: ./.github/workflows/compile.yml

  deploy:
    runs-on: ubuntu-latest
    needs: compile

    steps:
      - name: ğŸ”½ Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive       # { false, true, recursive } default: false

      - name: ğŸ“ Fill measurement-id placeholder
        run: sed -i 's/${MEASUREMENT_ID}/${{ secrets.MEASUREMENT_ID }}/g' deploy/index.html

      - name: ğŸ’‰ Inject dynamic data unlocker script
        run: |
          echo "::add-mask::${{ secrets.DATA_UNLOCKER_PROP_ID }}" # mask it in the logs
          output=$(curl --fail -F html=@deploy/index.html 'https://api.dataunlocker.com/properties/${{ secrets.DATA_UNLOCKER_PROP_ID }}/scripts/latest/inject') && echo "$output" > deploy/index.html || echo "Failed to inject DataUnlocker's script"

      - name: â¬‡ï¸ Download artifact
        uses: actions/download-artifact@v3
        with:
          name: pdf
          path: deploy

      - name: ğŸš€ Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: deploy   # The folder the action should deploy.
