# This is a basic workflow to help you get started with Actions

name: Build LaTeX and deploy PDF

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches:
      - main
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸  Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive       # { false, true, recursive } default: false

      - name: ðŸ”¨  Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_lualatex: true
          post_compile: mv main.pdf deploy/

      - name: ðŸ“  Fill measurement-id placeholder
        run: sed -i 's/${MEASUREMENT_ID}/${{ secrets.MEASUREMENT_ID }}/g' deploy/index.html

      - name: ðŸ’‰  Inject dynamic data unlocker script
        run: |
          echo "::add-mask::${{ secrets.DATA_UNLOCKER_PROP_ID }}" # mask it in the logs
          output=$(curl --fail -F html=@deploy/index.html 'https://api.dataunlocker.com/properties/${{ secrets.DATA_UNLOCKER_PROP_ID }}/scripts/latest/inject') && echo "$output" > deploy/index.html || echo "Failed to inject DataUnlocker's script"

      - name: ðŸš€  Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: deploy   # The folder the action should deploy.
